# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v29 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=0
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v30 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=-2
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v31 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=-0.5
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v32 --env_cfg_updates rewards.scales.stand_foot_orient_v3=-5 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=-1 footpoint.epsilon=0.005 
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v33 --env_cfg_updates rewards.scales.stand_foot_orient_v3=-5 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=-1 footpoint.epsilon=0.015
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v34 --env_cfg_updates rewards.scales.stand_foot_orient_v3=-5 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=-1 footpoint.epsilon=0.02
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v35 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=-1 footpoint.epsilon=0.005 
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v36 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=-1 footpoint.epsilon=0.015
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v37 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=-1 footpoint.epsilon=0.02
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v38 --env_cfg_updates rewards.scales.stand_foot_orient_v3=-5 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=0
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v39 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=-2 rewards.scales.stand_foot_vel_v2=-0.2 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_planar_contact=-0.2
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v40 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_planar_contact=-0.5
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v41 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_planar_contact=-0.2
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v42 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_planar_contact=-0.5 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v43 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_planar_contact=-0.2 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v44 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_planar_contact=-0.5 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_test_v45 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_planar_contact=-0.2 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v46 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque=-0.0002 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v47 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque=-0.0001 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v48 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque=-0.0003 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v49 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque=-0.0004 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v50 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque=-0.0005 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v51 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque=-0.0002 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v52 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque=-0.0002 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v53 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque=-0.0002 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v54 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque_v2=-0.5 rewards.scales.stand_ankle_limit=-0.5 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v55 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque_v2=-0.5 rewards.scales.stand_ankle_limit=0 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v56 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque_v2=0 rewards.scales.stand_ankle_limit=-0.5 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v57 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque_v2=-1 rewards.scales.stand_ankle_limit=0 footpoint.epsilon=0.005
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v58 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 rewards.scales.stand_zmp_supp_dist=-1 rewards.scales.stand_ankle_torque_v2=-0.5 rewards.scales.stand_ankle_limit=-0.5 footpoint.epsilon=0.01
# PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v59 --env_cfg_updates rewards.scales.stand_foot_orient_v3=0 rewards.scales.stand_foot_height=0 rewards.scales.stand_foot_vel_v2=0 footpoint.epsilon=0.01
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v60 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=1 footpoint.epsilon=0.01
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v61 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=0 footpoint.epsilon=0.01
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v62 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=0.5 footpoint.epsilon=0.01
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v63 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=2 footpoint.epsilon=0.01
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v64 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=1 footpoint.epsilon=0.005
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v65 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=0 footpoint.epsilon=0.005
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v66 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=0.5 footpoint.epsilon=0.005
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v67 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=2 footpoint.epsilon=0.005
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v68 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=0 rewards.scales.stand_zmp_margin=1 footpoint.epsilon=0.005
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v69 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=1 footpoint.epsilon=0.005 domain_rand.max_push_force_xy=1000
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v70 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=0 footpoint.epsilon=0.005 domain_rand.max_push_force_xy=1000
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v71 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=0.5 footpoint.epsilon=0.005 domain_rand.max_push_force_xy=1000
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v72 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=1 footpoint.epsilon=0.005 domain_rand.max_push_force_xy=20000
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v73 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=0 footpoint.epsilon=0.005 domain_rand.max_push_force_xy=20000
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v74 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=0.5 footpoint.epsilon=0.005 domain_rand.max_push_force_xy=20000
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v75 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=1 footpoint.epsilon=0.005 domain_rand.max_push_force_xy=0
PYTORCH_JIT=0 python3 legged_gym/scripts/train.py --task=g1_stand --num_envs=6000 --headless --run_name=stand_v76 --env_cfg_updates rewards.scales.stand_ankle_limit=-0.5 rewards.scales.stand_zmp_dist=-0.5 rewards.scales.stand_zmp_margin=1 footpoint.epsilon=0.005 domain_rand.max_push_force_xy=5000