events:
  - t: 3.0
    body: RF       
    pos: [0.0, -0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 3.0
    body: LF       
    pos: [0.0, 0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 3.5
    body: RF       
    pos: [0.0, -0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 4.0
    body: LF       
    pos: [0.0, 0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 4.5
    body: RF       
    pos: [0.0, -0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 5.0
    body: LF       
    pos: [0.3, 0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 5.5
    body: RF       
    pos: [0.6, -0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 6.0
    body: LF       
    pos: [0.9, 0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 6.5
    body: RF       
    pos: [1.2, -0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 7.0
    body: LF       
    pos: [1.5, 0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 7.5
    body: RF       
    pos: [1.8, -0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 8.0
    body: LF       
    pos: [2.1, 0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 8.5
    body: RF       
    pos: [2.1, -0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 9.0
    body: LF       
    pos: [2.1, 0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]
  - t: 9.5
    body: RF       
    pos: [2.1, -0.15, 0.0]
    quat: [1.0, 0.0, 0.0, 0.0]