# 
control_dt: 0.02

msg_type: "hg"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"


motor_joint: [
    'left_hip_pitch_joint',
    'left_hip_roll_joint',
    'left_hip_yaw_joint',
    'left_knee_joint',
    'left_ankle_pitch_joint',
    'left_ankle_roll_joint',
    'right_hip_pitch_joint',
    'right_hip_roll_joint',
    'right_hip_yaw_joint',
    'right_knee_joint',
    'right_ankle_pitch_joint',
    'right_ankle_roll_joint',
    'waist_yaw_joint',
    'waist_roll_joint',
    'waist_pitch_joint',
    'left_shoulder_pitch_joint',
    'left_shoulder_roll_joint',
    'left_shoulder_yaw_joint',
    'left_elbow_joint',
    'left_wrist_roll_joint',
    'left_wrist_pitch_joint',
    'left_wrist_yaw_joint',
    'right_shoulder_pitch_joint',
    'right_shoulder_roll_joint',
    'right_shoulder_yaw_joint',
    'right_elbow_joint',
    'right_wrist_roll_joint',
    'right_wrist_pitch_joint',
    'right_wrist_yaw_joint',
]

lab_joint: [
    'left_hip_pitch_joint',
    'right_hip_pitch_joint',
    'waist_yaw_joint',
    'left_hip_roll_joint',
    'right_hip_roll_joint',
    'waist_roll_joint',
    'left_hip_yaw_joint',
    'right_hip_yaw_joint',
    'waist_pitch_joint',
    'left_knee_joint',
    'right_knee_joint',
    'left_shoulder_pitch_joint', #11
    'right_shoulder_pitch_joint', #12
    'left_ankle_pitch_joint', #13
    'right_ankle_pitch_joint', #14
    'left_shoulder_roll_joint', #15
    'right_shoulder_roll_joint', #16
    'left_ankle_roll_joint',
    'right_ankle_roll_joint',
    'left_shoulder_yaw_joint', #19
    'right_shoulder_yaw_joint',
    'left_elbow_joint',
    'right_elbow_joint',
    'left_wrist_roll_joint',
    'right_wrist_roll_joint',
    'left_wrist_pitch_joint',
    'right_wrist_pitch_joint',
    'left_wrist_yaw_joint',
    'right_wrist_yaw_joint'
]

kps: [
    200, 150, 150, 200, 20, 20, # left leg
    200, 150, 150, 200, 20, 20, # right leg
    150, 150, 150,              # waist
    40, 40, 40, 40, 40, 40, 40, # left arm
    40, 40, 40, 40, 40, 40, 40  # right arm
]

kds: [
    5, 5, 5, 5, 2, 2, # left leg
    5, 5, 5, 5, 2, 2, # right leg
    5, 5, 5,              # waist
    10, 10, 10, 10, 10, 10, 10, # left arm
    10, 10, 10, 10, 10, 10, 10  # right arm
]



lab_joint_offsets: [
  -0.2000, -0.2000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
  0.0000,  0.4200,  0.4200, 0.4000, 0.4000, -0.2300, -0.2300,  0.1000,
  -0.1000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,  1.0000,  0.0000,
  0.0000,  0.0000,  0.0000,  0.0000,  0.0000
]


locomotion_policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/0926_l3_30k.pt"


initial_smoothing: 0.8
later_smoothing: 1.0
kpkd_smoothing: 1.
# sit_smoothing: 0.8
sit_smoothing: 0.8

locomotion_obs_dim: 113
num_actions: 29
